### ISSUE TITLE
writing unit test

### ISSUE THREAD

**Issue by s0h1s2** [dolanskurd/kurdish#2]
سڵاو ئەگەر پێت باشبێت ئەتوانیت هەندێک تێست بنووسیت بۆ گرتنی هەڵە تێدا

**Comment by 0xdolan** [comment]
دەست خۆش بەدڵنیایی پێویستییەتی بەڵام بەشێوازێکی درووستتر و ڕێکوپێکتر ئامادە دەکرێت لەداهاتوو. ئەویش ڕەچاو کراوە. سوپاس بۆ تێبینییەکەتان
