### ISSUE TITLE
گۆڕینی U+0647+U+200c ناگۆڕێت بۆ U+06d5

### ISSUE THREAD

**Issue by jwtiyar** [dolanskurd/kurdish#3]
سڵاو
I will Write in english because github dosen't support mix of kurdish and english texts:
I did select converting arabic characters to kurdish, which change none standard unicode to a standard unicode of kurdish letter, isn't it?
when i type a non standard one like U+0647+U+200c and it should change it to U+06d5, but it isn't.
ئەگەر سەیرێکی بکەیتەوە مەمنون بم نەوەک من هەڵەبم.

سوپاس

**Comment by 0xdolan** [comment]
سوپاس بۆ تێبینییەکەت کاکە جوتیار، ڕاستە وایە، دەست خۆش. چاکم کردووە بەس لەسەر پڕۆژەی تر ئیش دەکەم بۆیە مەجال نەبووە پووش بکەم. لە دەرفەتێک جێبەجێی دەکەم.

**Comment by jwtiyar** [comment]
> سوپاس بۆ تێبینییەکەت کاکە جوتیار، ڕاستە وایە، دەست خۆش. چاکم کردووە بەس لەسەر پڕۆژەی تر ئیش دەکەم بۆیە مەجال نەبووە پووش بکەم. لە دەرفەتێک جێبەجێی دەکەم.

دەستەکانت خۆش، نامەکەم کردە ئینگلیزی چونکە پیتەکان تێکەڵ دەبوون .
