### ISSUE TITLE
Provide a REST API

### ISSUE THREAD

**Issue by AramRafeq** [dolanskurd/kurdish#4]
Hi thanks for the effort this repo would so useful if you provided a restful API to transliterate from various strings i have faced this issue to convert kurdish text to its english representation when i had to generate referral codes from account name.

**Comment by 0xdolan** [comment]
Thanks Kak Aram,

Actually I will try, it has so many issues, I know, but a better project will be published, a much more perfect one, along with fixing all the issues. Please let me know if there is any other recommendation or  issues. Thanks again.
